version: "3"

services:
  centos7: &centos
    image: rpmbuild/centos7
    volumes:
    - .:/workspace
    entrypoint: /workspace/build_rpm.sh

  centos6:
    <<: *centos
    image: rpmbuild/centos6

  centos8:
    image: dalibo/labs-sdk:centos8
    volumes:
    - .:/workspace
    entrypoint: /workspace/build_rpm.sh
